# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1J64yV6QWvlRGhhGcCps0HtzlMQmRnj
"""

import pandas as pd
import joblib
import streamlit as st

# Title
st.title("🌦️ Rainfall Prediction App")
st.write("Enter location and date to predict rain.")

# Load model using joblib
model = joblib.load("rainfall_prediction_model.pkl")

# User Inputs
latitude = st.number_input("Latitude (°)", value=21.14631)
longitude = st.number_input("Longitude (°)", value=79.08491)
date = st.date_input("Select Date")

# Convert date to numeric format (if your model was trained with e.g., YYYYMMDD)
date_numeric = int(date.strftime("%Y%m%d"))

# Make dataframe
input_df = pd.DataFrame([{
    "latitude": latitude,
    "longitude": longitude,
    "date": date_numeric
}])

# Predict button
if st.button("Predict ☁️"):
    prediction = model.predict(input_df)

    if prediction[0] == 1:
        st.error("🌧️ Rain is expected on this day.")
    else:
        st.success("☀️ No rain expected on this day.")

